apiVersion: apps/v1
kind: Deployment
metadata:
  name: # deployment_name
  labels:
    app: # app-label # same as pod label # same as selector label in deployment
spec:
  replicas: 2 # number of pods  you want to run
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app # pod-label same as service label # make sure both are same
    spec:
      containers:
      - name: # container_name
        image: # which image
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: # service-name
  labels:
    app: # app-label same as pod label # to select the deployment pods 
spec:
  type: NodePort
  selector:
    app: calculator-app
  ports:
  - protocol: TCP
    port: 80                  # service-port
    targetPort: 5000          # pod-port
    nodePort: 30080           # node-port i.e..30000 to 32767