apiVersion: apps/v1
kind: Deployment
metadata:
  name: # deployment_name
  labels:
    app: calculator-app
spec:
  replicas: 2  # number of pods you want to run
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: # container_name
        image: # which image
        ports:
        - containerPort: 5000