apiVersion: apps/v1
kind: Deployment
metadata:
  name: # deployment_name
  labels:
    app: calculator-app
spec:
  replicas: 2  # number of pods you want to run
  strategy:
    type: RollingUpdate
      maxSurge: 1          
      # Kubernetes can create 1 extra new pod 
      # Helps bring new version up safely
      maxUnavailable: 0    
      # No pod is taken down until new pod is ready 
      # Ensures 100% availability
      # ðŸ‘‰ This is a safe production-style configuration
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: # container_name
        image: # which image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

